
package weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherService", targetNamespace = "http://Weather/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeatherByCityname", targetNamespace = "http://Weather/", className = "weather.GetWeatherByCityname")
    @ResponseWrapper(localName = "getWeatherByCitynameResponse", targetNamespace = "http://Weather/", className = "weather.GetWeatherByCitynameResponse")
    @Action(input = "http://Weather/WeatherService/getWeatherByCitynameRequest", output = "http://Weather/WeatherService/getWeatherByCitynameResponse")
    public String getWeatherByCityname(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
